title: AwesomeInc Bootcamp Blog
author: Evan Wilson
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a simple description because I'm not entirely sure what will go here.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
